### ISSUE TITLE
Do you have an .xml file to share for this as well?

### ISSUE THREAD

**Issue by ScriptByScript** [tetsuwo/zabbix-memcached-template#1]

**Comment by tetsuwo** [comment]
thanks for comment :)
i have this xml file, please wait.

**Comment by ScriptByScript** [comment]
Any update?

**Comment by tetsuwo** [comment]
Sorry late reply.

I uploaded to here.
https://github.com/tetsuwo/zabbix-memcached-template/blob/master/templates/zbx_export_templates.xml
